# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacob Elias
email: jacobeelias@gmail.com
bio: "I'm a designer from Chicago, living in Seattle. In my free time I make/write/take-photos-of things and waterski/snowboard/rock climb."
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Jacob Elias. Full of designs, links, thoughts, and pictures.
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jelias.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _jelias_
github_username:  jelias
linkedin_username: jacobelias
dribbble_username: jelias


#Project URL
#permalink:  /projects/:title/

#collections

collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
sass:
    style: compressed

#Plugins
plugins:
    # - jekyll-minifier
    - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

  # - scope:
  #     path: "photos"
  #   values:
  #     height: {{ dimensions.height }}
  #     width: {{ dimensions.width }}
